FROM python:3.10-slim

WORKDIR /app

COPY . /app

# 安装项目依赖
RUN pip install --no-cache-dir .

ENV TRANSPORT=http
ENV PORT=8085
EXPOSE 8085

CMD ["python", "-m", "mcp_weather_server", "--mode", "streamable-http", "--host", "0.0.0.0", "--port", "8085"]
