FROM registry.cn-hangzhou.aliyuncs.com/library/python:3.10-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install dependencies and the package
RUN (uv venv .venv) && (. .venv/bin/activate) && (uv pip install -e .)

ENV TRANSPORT=http
ENV PORT=8085
EXPOSE 8085

CMD ["uv", "run", "python", "-m", "mcp_weather_server", "--mode", "streamable-http", "--host", "0.0.0.0", "--port", "8085"]
